// ATCV Self-Test — Part 3 (L19–L25 question data)
window.S_PART_3 = [
{"id":"l19_1","ch":"l1920","g":"l1920-core","ct":"Lectures 19–20","cs":"Optical Flow","sc":null,"tit":"Brightness Constancy & Horn-Schunck","b":"L19 · §01","q":[
{"p":"State the 2-D motion constraint equation derived from brightness constancy.","o":["I_x + I_y + I_t = 0","I_x · u + I_y · v + I_t = 0","u + v = I_t / I_x","I · ∇u = 0"],"c":1,"e":"Brightness constancy: I(x,y,t) = I(x+δx, y+δy, t+δt). Taylor-expanding and dividing by δt gives I_x·u + I_y·v + I_t = 0 — one equation per pixel in two unknowns (u, v).","tag":null},
{"p":"What is the aperture problem?","o":["The image has too few pixels","One equation in two unknowns per pixel — only the gradient-aligned motion component is recoverable from a single window","Optical flow requires a calibrated camera","The image must be greyscale"],"c":1,"e":"The motion-along-the-edge is invisible to a single small window — you only see motion crossing the edge. A second constraint (smoothness, Lucas-Kanade local windowing, or a global energy term) is needed.","tag":null},
{"p":"How does Horn-Schunck add the second constraint?","o":["By assuming velocity is constant in time","Global smoothness term: minimise E = ∫ (I_x u + I_y v + I_t)² + α²·((u−ū)² + (v−v̄)²) dx dy","By computing the Hessian at every pixel","By using a learned CNN"],"c":1,"e":"Add a regulariser penalising deviation of (u,v) from local averages — neighbouring pixels should have similar flow. α weights smoothness vs data fidelity; solved iteratively until convergence.","tag":null},
{"p":"Given I(t) = [[3,5],[3,5]] and I(t+1) = [[4,6],[3,5]], the standard finite-difference estimators give:","o":["I_x = 8, I_y = 2, I_t = 2","I_x = 2, I_y = 8, I_t = 0","I_x = 4, I_y = 4, I_t = 4","I_x = 0, I_y = 0, I_t = 2"],"c":0,"e":"I_x = (right) − (left) summed across both frames = 21 − 13 = 8. I_y = (top) − (bottom) = 18 − 16 = 2. I_t = (next frame) − (current frame) = 18 − 16 = 2. The constraint 8u + 2v + 2 = 0 has infinite solutions — aperture problem.","tag":null},
{"p":"Horn-Schunck's smoothness assumption breaks down at:","o":["Image centres","Motion boundaries between differently-moving objects","Stationary regions","Specular highlights"],"c":1,"e":"Neighbouring pixels at the boundary of two differently-moving objects do NOT have similar flow. Modern methods use edge-aware smoothness or piecewise-smooth regularisers; deep flow networks (FlowNet, PWCNet, RAFT) learn the prior directly.","tag":null}
]},

{"id":"l21_1","ch":"l21","g":"l21-gan","ct":"Lecture 21","cs":"GANs","sc":null,"tit":"GAN Training & Min-Max Loss","b":"L21 · §01","q":[
{"p":"In a GAN, what does the generator G do?","o":["Classifies real vs fake images","Maps a noise vector z to a fake image, attempting to fool the discriminator","Trains the discriminator","Computes gradient-domain composites"],"c":1,"e":"G(z) maps a low-D noise (typically 100-D Gaussian) to a fake image; D classifies real vs fake. They train alternately — D learns to discriminate, G learns to fool D.","tag":null},
{"p":"Goodfellow's original GAN min-max objective is:","o":["min_G min_D L","max_G max_D L","min_G max_D E[log D(x)] + E[log(1 − D(G(z)))]","Both networks minimise cross-entropy independently"],"c":2,"e":"D maximises its ability to discriminate, G minimises D's ability to spot fakes. At Nash equilibrium, G samples from the data distribution and D is at chance (50%).","tag":null},
{"p":"What is mode collapse?","o":["The discriminator stops learning","The generator outputs only one (or a few) images that fool D — losing diversity across the data distribution","Training data exhaustion","The loss diverges to infinity"],"c":1,"e":"G discovers a narrow set of outputs that consistently fool D; the network synthesises essentially the same image for every z. Mitigations: mini-batch discrimination, Wasserstein loss + gradient penalty, spectral normalisation, TTUR.","tag":null}
]},
{"id":"l21_2","ch":"l21","g":"l21-rep","ct":"Lecture 21","cs":"GAN Variants & Representation Learning","sc":null,"tit":"cGAN vs CycleGAN, SimCLR, VAE, DIP","b":"L21 · §02","q":[
{"p":"Key data-requirement difference between cGAN (pix2pix) and CycleGAN?","o":["cGAN is unsupervised; CycleGAN is supervised","pix2pix requires paired (x, y) data; CycleGAN works with unpaired collections {x}∈X and {y}∈Y, regularised by cycle-consistency F(G(x)) ≈ x","Both require paired data","CycleGAN does not use a discriminator"],"c":1,"e":"pix2pix needs each input matched to its exact GT (paired sketch+photo of same shoe). CycleGAN's cycle-consistency loss anchors G:X→Y and F:Y→X to be near-inverses, removing the paired-data requirement.","tag":null},
{"p":"The 'projection head' trick in SimCLR is:","o":["A small attention block","Compute contrastive loss on g(f(x)), a 1–2 layer MLP applied AFTER the encoder; discard g for downstream tasks","Concatenate positional embeddings","A second discriminator"],"c":1,"e":"Computing NT-Xent on g(f(x)) instead of f(x) gives ~10% linear-probe accuracy boost. After pre-training, g is discarded and only f is used — the head absorbs task-specific information that would hurt transfer.","tag":null},
{"p":"How does a VAE differ from a standard autoencoder?","o":["VAEs have no decoder","Encoder outputs Gaussian parameters (μ, σ²); latent z is sampled (with the reparameterisation trick); loss adds KL divergence to N(0, I) prior","VAEs use convolutional layers; standard AEs do not","VAEs are deterministic at inference"],"c":1,"e":"The KL term forces the latent to behave like N(0, I); sampling z = μ + σ·ε keeps gradients flowing through stochasticity. This regularises the latent so points near the origin all decode plausibly — enables generation and smooth interpolation.","tag":null},
{"p":"Deep Image Prior (DIP) works because:","o":["The MLP has learned natural-image statistics","The encoder-decoder CNN architecture itself prefers smooth, locally-coherent outputs and resists fitting high-frequency noise — early-stopped training captures the clean image","Random weights happen to be optimal","DIP uses gradient-domain inpainting"],"c":1,"e":"Convolution + multi-scale + skip-connections form a strong implicit prior. Train an untrained CNN to map fixed-noise input → noisy target by MSE; early stopping captures the moment when low-frequency content is learned but high-frequency noise is not yet memorised.","tag":null}
]},

{"id":"l22_1","ch":"l2225","g":"l2225-vl","ct":"Lectures 22–25","cs":"Vision-Language · Detection · 3D · Sketch","sc":null,"tit":"RNN/LSTM & CLIP","b":"L22 · §01","q":[
{"p":"How does an LSTM's cell state help with long-range dependencies?","o":["By dropping gates that are not active","Acts as a 'memory highway': forget/input gates control multiplicative attenuation; gradients flow additively through C_t, avoiding vanishing","Cell state is detached from gradients","LSTM trains separately for each time-step"],"c":1,"e":"f_t ≈ 1 + i_t ≈ 0 lets information persist many steps. The additive update C_t = f_t·C_{t-1} + i_t·Č_t means gradients don't get multiplied by tiny derivatives at every step — fixes the vanishing-gradient problem of vanilla RNNs.","tag":null},
{"p":"In 'Show and Tell' (CNN + LSTM captioning), where does the CNN's output enter the LSTM?","o":["At every time-step as additional input","As the LSTM's initial hidden/cell state","After the softmax","Through an attention bottleneck"],"c":1,"e":"The fixed-size image embedding initialises the LSTM state; the LSTM then unrolls one word at a time, taking the previous predicted word as input. Modern variants ('Show, Attend and Tell') add per-step attention over the CNN's spatial feature map.","tag":null},
{"p":"What is the principal innovation of CLIP?","o":["A new convolutional architecture","Trained on 400M (image, caption) web pairs with symmetric contrastive loss in a shared embedding — enables zero-shot transfer via natural-language prompts","First model to use ReLU","Generated images for the first time"],"c":1,"e":"WIT (Web Image-Text) supplied natural-language supervision at ~330× ImageNet's scale. Contrastive training in a shared embedding lets CLIP classify into any text-defined categories at inference — zero-shot — and underpins open-vocabulary detection/segmentation and prompts for DALL-E/Stable Diffusion.","tag":null},
{"p":"NT-Xent (SimCLR) loss with temperature τ is:","o":["MSE between two views","L = − log(exp(sim(z_i, z_j)/τ) / Σ_{k≠i} exp(sim(z_i, z_k)/τ))","Cross-entropy with hard one-hot labels","Hinge loss with margin τ"],"c":1,"e":"Normalised temperature-scaled cross-entropy: the positive pair (z_i, z_j) is the numerator; all other in-batch views are the denominator. τ scales the similarities; smaller τ → sharper distribution.","tag":null}
]},

{"id":"l23_1","ch":"l2225","g":"l2225-det","ct":"Lecture 23","cs":"Object Detection","sc":null,"tit":"R-CNN → Faster R-CNN → DETR","b":"L23 · §01","q":[
{"p":"Main reason Fast R-CNN is faster than R-CNN?","o":["Smaller backbone CNN","Run CNN forward pass on the WHOLE image once; share the feature map across all proposals via RoI Pooling — instead of ~2000 separate CNN passes","Eliminates region proposals","Replaces softmax with SVMs"],"c":1,"e":"R-CNN re-runs the CNN per region (~2000× per image). Fast R-CNN's RoI Pooling pools the shared feature map at each proposal's location to a fixed-size patch (e.g. 7×7), reducing per-region cost to a few small FC layers — ~100× faster inference.","tag":null},
{"p":"What does Faster R-CNN replace selective search with?","o":["A Transformer encoder","A Region Proposal Network (RPN) that shares the backbone feature map and predicts objectness + box offsets relative to anchor boxes","Edge detection","Manual region selection"],"c":1,"e":"The RPN slides over the shared feature map, predicting objectness and anchor-box offsets at each location. Trained jointly with the detector head, runs in milliseconds inside the GPU pipeline — drops inference from ~2 s to ~0.2 s/image.","tag":null},
{"p":"Headline architectural innovation of DETR?","o":["First detector with ResNet backbone","Set prediction via Transformer + Hungarian matching — no anchors, no proposals, no NMS","Uses CycleGAN losses","Anchor-free regression in CNN space"],"c":1,"e":"DETR's decoder takes N learned object queries that cross-attend to the image features and produce one (class, box) each. Bipartite Hungarian matching during training forces unique predictions per object; NMS is no longer needed.","tag":null},
{"p":"Why does adding a Feature Pyramid Network (FPN) improve detection?","o":["Reduces parameter count","Combines feature maps from multiple backbone stages (top-down + lateral) — detection can happen at the appropriate scale per object, especially helping small objects","Replaces RoI Pooling with attention","Removes the need for an objectness score"],"c":1,"e":"Single-scale features lose small objects at the final low-resolution map. FPN's multi-scale features let small objects use high-resolution early layers and large objects use semantic late layers — single biggest accuracy gain on COCO.","tag":null},
{"p":"Compared to Faster R-CNN, the principal DOWNSIDE of the original DETR?","o":["Lower accuracy by 30%","Slow training convergence (~500 epochs vs ~50 for Faster R-CNN); weaker on small objects in its original single-scale form","Requires labelled segmentation masks","Cannot be GPU-accelerated"],"c":1,"e":"Vanilla DETR converges slowly because each query must learn to attend to a unique object via bipartite matching — a non-trivial bootstrapping. Deformable DETR, DINO, RT-DETR fix both convergence and small-object handling.","tag":null}
]},

{"id":"l24_1","ch":"l2225","g":"l2225-3d","ct":"Lecture 24","cs":"3-D Vision","sc":null,"tit":"3-D Representations, PointNet & PIFu","b":"L24 · §01","q":[
{"p":"Which 3-D representation requires a permutation-invariant network?","o":["Voxel grid","Mesh","Point cloud","Depth image"],"c":2,"e":"A point cloud is an unordered set: shuffling points represents the same shape. PointNet achieves invariance by (i) shared MLP per point (equivariant) (ii) max-pool over all points (symmetric aggregation).","tag":null},
{"p":"PointNet aggregates per-point features with which symmetric function?","o":["Sum","Concatenation","Element-wise max-pooling","Cross-attention"],"c":2,"e":"Max-pooling is permutation-invariant and empirically robust to noise. Sum and product also satisfy invariance but max works best — Qi et al. (CVPR 2017) showed max-pool keeps the most distinctive features across the set.","tag":null},
{"p":"Memory cost of a voxel grid at resolution N is:","o":["O(N)","O(N²)","O(N³)","O(N log N)"],"c":2,"e":"O(N³). At 256³ a dense voxel grid is ~16M cells — prohibitive at high resolution. Sparse voxel structures (Octrees, hash grids) partially mitigate this.","tag":null},
{"p":"What is the main motivation behind PIFu (Pixel-Aligned Implicit Function)?","o":["Train detectors faster","Avoid the resolution/topology limits of voxels and meshes by predicting an implicit occupancy function MLP(p, F) — the surface is the zero level-set, extracted via Marching Cubes","Replace SDFs with point clouds","Speed up rendering"],"c":1,"e":"PIFu (Saito et al., ICCV 2019) conditions each 3-D query point on a pixel-aligned image feature sampled from the projected image location, then asks an MLP for occupancy. Combines rich 2-D CNN features with continuous 3-D output of arbitrary resolution and topology.","tag":null},
{"p":"Marching Cubes converts what into what?","o":["Mesh → voxel","SDF / implicit volumetric field → triangle mesh by interpolating zero-crossings on cube edges","RGB → depth","Voxel → point cloud"],"c":1,"e":"For each cube in a 3-D grid, evaluate the field at 8 corners; the inside/outside pattern (256 cases, 15 unique up to symmetry) determines which triangles to emit, with each vertex's exact position found by linear interpolation along the cube edge it sits on.","tag":null}
]},

{"id":"l25_1","ch":"l2225","g":"l2225-nerf","ct":"Lecture 25","cs":"NeRF & Sketch","sc":null,"tit":"NeRF & Sketch-Based Retrieval","b":"L25 · §01","q":[
{"p":"NeRF represents a scene as a function of:","o":["3-D position only","2-D pixel + RGB","5-D (3-D position + 2-D viewing direction) → (density σ, view-dependent RGB c)","Stereo disparity"],"c":2,"e":"F_Θ(x, y, z, θ, φ) = (σ, c). Density is view-independent (geometry), colour depends on viewing direction (specular highlights move with the camera). Positional encoding lifts the 5-D input to a high-frequency basis so the MLP can model fine detail.","tag":null},
{"p":"NeRF renders a pixel by:","o":["Single MLP forward pass per pixel","Casting a ray, sampling many points along it, querying the MLP at each, and integrating via volume rendering C(r) = Σ T_i·(1−exp(−σ_i·δ_i))·c_i","Bicubic interpolation","Marching cubes followed by rasterisation"],"c":1,"e":"The volume-rendering integral accumulates view-dependent colour weighted by density and accumulated transmittance T_i along the ray. Differentiable end-to-end — MLP weights are optimised by gradient descent on per-pixel MSE.","tag":null},
{"p":"NeRF's biggest practical limitation in its original 2020 form:","o":["Cannot handle outdoor scenes","Per-scene training (no generalisation) and slow rendering (many MLP queries per pixel); ~12h training per scene originally","Requires segmentation masks","Limited to 32×32 outputs"],"c":1,"e":"Each scene needs its own MLP; rendering is slow because each pixel needs many MLP queries along its ray. Subsequent work — InstantNGP (hash grids), Plenoxels (voxel + spherical harmonics), Gaussian Splatting — reduces training to seconds and enables real-time rendering.","tag":null},
{"p":"Why is sketch a useful modality for fine-grained retrieval?","o":["Sketches contain colour and lighting","Sketch encodes precise shape/silhouette information difficult to express in text, and is language-agnostic — ideal for instance-level 'find this exact object' queries","Sketches are always paired with photos","Sketch retrieval requires less compute"],"c":1,"e":"For 'find THIS shoe' (instance-level), sketches capture proportions and outline cues text cannot. Universal and language-independent. Main challenge: sketch is subjective — different users draw the same object very differently, making generalisation across drawers the central SBIR difficulty.","tag":null}
]}
];
