// ATCV Self-Test — Part 1 (Linear Algebra + L1–L11 question data)
window.S_PART_1 = [
{"id":"la1","ch":"la","g":"la-core","ct":"Linear Algebra Revision","cs":"2-D Transformations & Homogeneous Coordinates","sc":null,"tit":"Matrices, Linear Maps & Translation","b":"LA · §01","q":[
{"p":"Why can a 2×2 matrix not represent a translation in the plane?","o":["Because 2×2 matrices have determinant 1","Because linear transformations must fix the origin, and translation does not","Because translations require complex numbers","Because matrix addition is undefined for 2×2"],"c":1,"e":"Linear maps satisfy T(0)=0; translation by a non-zero vector moves the origin, so it cannot be encoded as a 2×2 multiplication. Homogeneous coordinates lift the problem into 3-D so translation becomes a 3×3 matrix multiplication.","tag":null},
{"p":"In homogeneous coordinates the point (x, y) is represented as (x, y, 1). Which 3×3 matrix translates it by (dx, dy)?","o":["[[1,0,dx],[0,1,dy],[0,0,1]]","[[dx,0,1],[0,dy,1],[0,0,1]]","[[1,0,0],[0,1,0],[dx,dy,1]]","[[1,dx,0],[dy,1,0],[0,0,1]]"],"c":0,"e":"T = [[1,0,dx],[0,1,dy],[0,0,1]] · [x; y; 1] = [x+dx; y+dy; 1]. The dx/dy entries sit in the right column so they interact additively with the trailing 1 in the homogeneous vector.","tag":null},
{"p":"Composing T(dx₁, dy₁) followed by T(dx₂, dy₂) is equivalent to what single transformation?","o":["T(dx₁·dx₂, dy₁·dy₂)","T(dx₁ + dx₂, dy₁ + dy₂)","Identity (translations cancel)","T(max(dx₁,dx₂), max(dy₁,dy₂))"],"c":1,"e":"Multiplying the two homogeneous translation matrices yields a translation by the vector sum (dx₁+dx₂, dy₁+dy₂). Successive translations are simply additive.","tag":null}
]},
{"id":"la2","ch":"la","g":"la-core","ct":"Linear Algebra Revision","cs":"2-D Transformations & Homogeneous Coordinates","sc":null,"tit":"Rotation, Scale & Composition","b":"LA · §02","q":[
{"p":"Apply the scale matrix S = [[2,0],[0,0.5]] to point P = (3, 4)^T. What is S·P?","o":["(5, 4.5)","(6, 2)","(1.5, 8)","(3, 4)"],"c":1,"e":"S·P = (2·3, 0.5·4) = (6, 2). Horizontal stretch by 2, vertical compression by 0.5.","tag":null},
{"p":"To rotate by θ about an arbitrary centre (cx, cy), the standard composition is M = ?","o":["T(cx, cy) · R(θ) · T(−cx, −cy)","T(−cx, −cy) · R(θ) · T(cx, cy)","R(θ) · T(cx, cy)","R(θ) only — translation is irrelevant"],"c":0,"e":"Translate the centre to the origin first (T(−cx,−cy)), rotate (R(θ)), then translate back (T(cx,cy)). Order matters because matrix multiplication is non-commutative.","tag":null},
{"p":"Why does the composition order matter for affine transformations?","o":["Determinant changes with order","Matrix multiplication is non-commutative in general","Translations would be lost","It does not — order is irrelevant"],"c":1,"e":"AB ≠ BA in general for matrices. Rotate-then-translate produces a different result from translate-then-rotate.","tag":null}
]},

{"id":"l1_1","ch":"l1l4","g":"l1l4-l1","ct":"Lectures 1–4","cs":"Representation · Colour · Warping","sc":null,"tit":"Framebuffers & Pixel Addressing","b":"L1 · §01","q":[
{"p":"What is the address of the Red byte for pixel (x, y) = (2, 1) in a W×H RGB888 framebuffer?","o":["x + W·y = 2 + W","3·(x + W·y) = 3·(W + 2)","x·3 + W·y","W·y · 3 + x"],"c":1,"e":"RGB888 uses 3 bytes per pixel laid out row-major. Address of the R-byte = 3·(x + W·y); G byte at +1, B byte at +2.","tag":null},
{"p":"A 3000 × 2000 RGB888 image. Approximate framebuffer size (in MB, decimal)?","o":["~6 MB","~12 MB","~18 MB","~36 MB"],"c":2,"e":"3000·2000·3 = 18,000,000 bytes ≈ 18 MB decimal (≈ 17.17 MB binary).","tag":null}
]},
{"id":"l1_2","ch":"l1l4","g":"l1l4-l1","ct":"Lecture 1","cs":"Image Representation","sc":null,"tit":"Colour Models & Greyscale Conversion","b":"L1 · §02","q":[
{"p":"Which equation gives perceived-luminosity greyscale from normalised RGB?","o":["L = (R + G + B) / 3","L = 0.30R + 0.59G + 0.11B","L = max(R, G, B)","L = 0.11R + 0.30G + 0.59B"],"c":1,"e":"The ITU-R BT.601 luma weights (0.30, 0.59, 0.11) reflect the eye's higher sensitivity to green and low sensitivity to blue. Naïve averaging looks wrong.","tag":null},
{"p":"Why is CMYK preferred over CMY for printing?","o":["CMY is patented; CMYK is free","Mixing C+M+Y produces a muddy brown rather than a true black; K saves ink and sharpens text","Printers cannot deposit yellow without a black plate","K has a wider gamut than CMY combined"],"c":1,"e":"Pure black ink is darker and cheaper than mixing C+M+Y, and is rendered on a separate plate aligned to the printhead — sharper text with no mis-registration halos.","tag":null}
]},
{"id":"l1_3","ch":"l1l4","g":"l1l4-l1","ct":"Lecture 1","cs":"Image Representation","sc":null,"tit":"Gamma & Bayer Pattern","b":"L1 · §03","q":[
{"p":"A CRT's light output I relates to input pixel power P by I = P^γ. Typical γ for a CRT?","o":["1.0","1.5","2.2","3.6"],"c":2,"e":"γ ≈ 2.2 for a typical CRT. Even though CRTs are obsolete, sRGB keeps γ ≈ 2.2 in the transfer function, so the chain is self-consistent for sRGB-aware code.","tag":null},
{"p":"In a Bayer mosaic, why are there two green cells per 2×2 tile (vs one red and one blue)?","o":["Green dye is cheaper","Human vision is more sensitive to green; doubling green improves perceived luminance fidelity","Random pattern with no perceptual basis","CCD sensors are intrinsically green-sensitive"],"c":1,"e":"The 2:1:1 G:R:B ratio mimics the eye's higher green sensitivity, so the demosaiced luminance channel has better effective resolution.","tag":null}
]},

{"id":"l2_1","ch":"l1l4","g":"l1l4-l2","ct":"Lecture 2","cs":"Colour","sc":null,"tit":"CIE XYZ, Gamut & RGB↔CMYK","b":"L2 · §01","q":[
{"p":"Why can no 3-primary additive system reproduce every visible colour?","o":["Three primaries have insufficient brightness","The CIE chromaticity horseshoe is curved; any 3-primary system can only reach the triangle inside it","Gamma correction limits the gamut","Human eyes have only three cone types"],"c":1,"e":"With three primaries P₁, P₂, P₃ the reachable colours form a triangle in chromaticity space. The visible-colour locus (horseshoe) is curved, so some chromaticities always lie outside the triangle — the device gamut.","tag":null},
{"p":"Convert CMY = (0.2, 0.5, 0.6) to CMYK.","o":["(0.2, 0.5, 0.6, 0)","(0, 0.3, 0.4, 0.2)","(0.2, 0.5, 0.6, 0.2)","(0.4, 0.7, 0.8, 0.2)"],"c":1,"e":"K = min(C,M,Y) = 0.2; then C' = C−K = 0, M' = M−K = 0.3, Y' = Y−K = 0.4. CMYK = (0, 0.3, 0.4, 0.2).","tag":null},
{"p":"What does the CIE XYZ space's Y component represent?","o":["Yellow primary intensity","Luminance (perceived brightness)","Saturation","Wavelength of the dominant frequency"],"c":1,"e":"In CIE XYZ, Y is the luminance channel (constructed to track perceived brightness); X and Z together carry chromaticity. Hence the (x, y, Y) decomposition into chromaticity + luminance.","tag":null}
]},
{"id":"l2_2","ch":"l1l4","g":"l1l4-l2","ct":"Lecture 2","cs":"Colour","sc":null,"tit":"HSV Conversion & Interpolation","b":"L2 · §02","q":[
{"p":"Convert RGB = (0.2, 0.5, 0.7) to HSV. Approximate hue?","o":["~15° (red-orange)","~95° (green)","~195° (cyan/teal)","~290° (purple)"],"c":2,"e":"W = min = 0.2, V = max = 0.7, S = 1 − 0.2/0.7 ≈ 0.714. Subtract W → (0, 0.3, 0.5); min is R (=W) so add 120° (G→B arc); ratio 0.5/0.8 = 0.625 → 75°. H = 120° + 75° = 195° — cyan/teal, consistent with the blue-leaning input.","tag":null},
{"p":"Linear interpolation half-way between pure red and pure green: what mid-colour does each space give?","o":["Both give bright yellow","Both give dull olive","RGB → dull olive (0.5, 0.5, 0); HSV → bright pure yellow (1, 1, 0)","RGB → bright yellow; HSV → dull olive"],"c":2,"e":"RGB midpoint cuts a chord through the cube and dims the colour. HSV midpoint walks the wheel along its saturated rim and preserves brightness — bright pure yellow (H=60°, S=1, V=1).","tag":null},
{"p":"In the RGB→HSV algorithm, if the minimum component (W) equals B, which hue offset is added to the arc position?","o":["0° (R→G arc)","120° (G→B arc)","240° (B→R arc)","Always 60° regardless"],"c":0,"e":"Mnemonic: W = B → 0°, W = R → 120°, W = G → 240°. The arc you traverse is bounded by the two non-zero post-subtraction components; the offset comes from the missing (minimum) channel.","tag":null}
]},

{"id":"l3_1","ch":"l1l4","g":"l1l4-l3","ct":"Lectures 3–4","cs":"Digital Image Warping","sc":null,"tit":"Forward vs Backward Mapping","b":"L3 · §01","q":[
{"p":"Why does forward mapping leave visible holes in a rotated image?","o":["Rounding errors compound multiplicatively","Adjacent source pixels can map to the same/distant target locations, leaving many target pixels unwritten","Forward mapping does not handle colour channels","Forward mapping requires inv(M) which fails near singularities"],"c":1,"e":"Forward mapping iterates over source pixels and writes them into targets. After rotation many target pixels receive no source pixel ⇒ black speckles. Backward mapping (iterate over targets, ask source) visits every target exactly once and cannot leave holes.","tag":null},
{"p":"Where should inv(M) be computed in a backward-mapping warp implementation?","o":["Inside the inner per-pixel loop, every iteration","Once, outside the per-pixel loop","Twice per row","It does not matter — modern compilers optimise it"],"c":1,"e":"inv(M) is constant across pixels. Computing it inside the loop is enormously wasteful — hoist it outside. The lab demo ipv_warp_backward.m does exactly this.","tag":null},
{"p":"To ensure the entire source image is visible after a 45° rotation about the centre, what additional step is needed?","o":["Multiply by the determinant of M","Compute the bounding box of the four warped corners and translate so min(x), min(y) ≥ 0; size the target frame accordingly","Use only nearest-neighbour interpolation","Pre-clip the source to a circular mask"],"c":1,"e":"Warp the four corners under M, take min/max of each coordinate, add a final translation (−min_x, −min_y) to bring the result into the positive domain, and set target dimensions to max−min+1.","tag":null}
]},
{"id":"l3_2","ch":"l1l4","g":"l1l4-l3","ct":"Lectures 3–4","cs":"Digital Image Warping","sc":null,"tit":"Interpolation Strategies","b":"L3 · §02","q":[
{"p":"Pixels I(20,30)=200, I(21,30)=100, I(20,31)=50, I(21,31)=180. Bi-linear value at (20.4, 30.6)?","o":["~115","~125","~140","~165"],"c":1,"e":"Interpolate along y first: E(20,30.6) = 0.4·200 + 0.6·50 = 110; F(21,30.6) = 0.4·100 + 0.6·180 = 148. Then along x: I(20.4,30.6) = 0.6·110 + 0.4·148 = 125.2.","tag":null},
{"p":"After a 45° rotation followed by inverse rotation, typical MSE difference between bi-linear and nearest-neighbour?","o":["Bi-linear is ~10× worse than NN","Roughly equal","Bi-linear is roughly an order of magnitude better than NN (e.g. 0.05% vs 0.46%)","Bi-linear is 1000× better"],"c":2,"e":"Typical figures: NN ~0.46% MSE per round-trip, bi-linear ~0.05% — about 10× better. The gap widens with cumulative warps (28% vs 3.4%).","tag":null},
{"p":"Bi-cubic interpolation uses how many neighbouring pixels?","o":["4 (2×2)","9 (3×3)","16 (4×4)","25 (5×5)"],"c":2,"e":"Bi-cubic fits a piecewise-cubic surface over a 4×4 patch — 2 pixels each side in x and y around the sample point.","tag":null}
]},
{"id":"l3_3","ch":"l1l4","g":"l1l4-l3","ct":"Lectures 3–4","cs":"Digital Image Warping","sc":null,"tit":"Aliasing & Fant's Algorithm","b":"L3 · §03","q":[
{"p":"What is the Nyquist sampling rate requirement?","o":["At least the highest frequency present","At least twice the highest frequency present","At least 4× the highest frequency","No limit — any rate suffices"],"c":1,"e":"Nyquist: to reconstruct without aliasing you need at least 2× the highest frequency present. Under-sampling causes high frequencies to fold back as spurious low frequencies (moiré).","tag":null},
{"p":"The standard anti-aliasing strategy before a downscale-warp is to:","o":["Switch from bi-linear to nearest-neighbour","Apply a Gaussian low-pass filter (blur) to remove frequencies above the new Nyquist","Increase the bit-depth from 8-bit to 16-bit","Apply gamma correction"],"c":1,"e":"Pre-filter to band-limit the source so the highest remaining frequency is below half the new sampling rate. Some fine detail is lost, but the alternative — moiré waves and jagged edges — is worse.","tag":null},
{"p":"Why is backward mapping unsuitable when F is a non-invertible deformation field (e.g. morphing)?","o":["It runs too slowly for morphing","Backward mapping requires F⁻¹; no closed-form inverse exists for non-invertible F","Morphing requires nearest-neighbour exclusively","Backward mapping only handles rotation"],"c":1,"e":"Backward mapping queries M⁻¹ per target pixel. If F is non-invertible (e.g. a complex morph field) no inverse is available. Fant's 2-pass algorithm gives an efficient forward alternative — decompose into 1-D x-warp then 1-D y-warp.","tag":null}
]},

{"id":"l5_1","ch":"l5l7","g":"l5l7-l5","ct":"Lectures 5–7","cs":"Enhancement · Filtering · Edges","sc":null,"tit":"Histograms, Brightness & Contrast","b":"L5 · §01","q":[
{"p":"For the 9-pixel image [10,20,30; 40,50,60; 70,80,90], what is the variance?","o":["~225","~500","~667","~1200"],"c":2,"e":"Mean μ = 50. Σ(xᵢ−μ)² = 1600+900+400+100+0+100+400+900+1600 = 6000. σ² = 6000/9 ≈ 666.67.","tag":null},
{"p":"What does brightness manipulation do to the image's pdf?","o":["Translates it (shape preserved until clipping)","Mirrors it about the centre","Scales the spread (variance changes)","Reshapes it to uniform"],"c":0,"e":"g(x,y) = f(x,y) + C translates the pdf by C; the shape is preserved until clipping at 0 or 255 truncates the histogram tails.","tag":null},
{"p":"Can contrast stretching recover lost dynamic range (e.g. a source with only 50 distinct values)?","o":["Yes — the rescale fills in missing intensity levels","No — the same 50 values are just spread out; visible 'comb' gaps appear in the histogram","Yes, if combined with histogram equalisation","Only for greyscale images"],"c":1,"e":"Contrast stretching is a linear rescale; it cannot create new intensity values. Original 50 distinct levels become 50 spread-out levels with gaps between them.","tag":null}
]},
{"id":"l5_2","ch":"l5l7","g":"l5l7-l5","ct":"Lecture 5","cs":"Image Enhancement","sc":null,"tit":"Thresholding & Equalisation","b":"L5 · §02","q":[
{"p":"Otsu's method chooses the threshold T by:","o":["Picking the histogram's median value","Minimising within-class variance (equivalently maximising between-class variance) of the two pixel populations","Selecting the histogram's local minimum between peaks","Splitting at intensity 128 always"],"c":1,"e":"Otsu tries every T and picks the one that maximises σ²_B(T) = w₁(T)·w₂(T)·(μ₁−μ₂)². Equivalently minimises within-class variance — total variance = within + between, so they're complementary objectives.","tag":null},
{"p":"When does adaptive (window-based) thresholding outperform Otsu?","o":["Whenever the image has more than 1000 pixels","Under non-uniform illumination (e.g. document photographs with shadows)","Only for binary images","When the histogram is exactly uniform"],"c":1,"e":"Otsu picks a single global T — it fails when illumination varies across the image and no single T can segment foreground from background. Adaptive thresholding computes T locally per window (e.g. mean + offset) — standard for OCR.","tag":null},
{"p":"Histogram equalisation maps intensities through which transfer function?","o":["T(n) = log(p(n))","T(n) = (L−1) · cdf(n)","T(n) = exp(p(n))","T(n) = n^γ"],"c":1,"e":"Multiply the cumulative pdf by L−1 (e.g. 255 for 8-bit). This linearises the cdf and makes the output histogram approximately uniform — using the available dynamic range maximally.","tag":null}
]},

{"id":"l6_1","ch":"l5l7","g":"l5l7-l6","ct":"Lectures 6–7","cs":"Filtering & Edges","sc":null,"tit":"Noise, Convolution & Fourier","b":"L6 · §01","q":[
{"p":"Best filter for salt-and-pepper noise?","o":["3×3 box (mean) filter","Gaussian low-pass","Median filter","Sharpening kernel"],"c":2,"e":"S&P pixels are extreme outliers (0 or 255). A median filter sorts the neighbourhood values; the spikes land at the ends of the list and are discarded. A mean would smear each spike across the window.","tag":null},
{"p":"State the convolution theorem.","o":["Convolution in spatial domain = convolution in frequency domain","Convolution in spatial domain = element-wise multiplication in frequency domain (F[f*g] = F[f]·F[g])","Differentiation equals convolution in frequency domain","Multiplication in spatial domain = convolution in spatial domain"],"c":1,"e":"F[f*g] = F[f]·F[g]. Two practical consequences: (i) large-kernel convolution becomes O(N log N) via FFT-multiply-IFFT, (ii) filter design is easier in frequency than in space.","tag":null},
{"p":"Frequency response of a box filter vs Gaussian?","o":["Both are Gaussians","Box → sinc (oscillates, side-lobes); Gaussian → another Gaussian (smooth, monotonic)","Box → Gaussian; Gaussian → sinc","Both are sinc functions"],"c":1,"e":"FT of a rectangular box is a sinc function — oscillates with negative side-lobes, causing ringing at edges. FT of a Gaussian is another Gaussian (with reciprocal width 1/σ) — smooth, no ringing.","tag":null},
{"p":"For additive Gaussian noise across N captures, by what factor does averaging reduce noise?","o":["N","√N","N²","log N"],"c":1,"e":"Central limit theorem: averaging N independent zero-mean Gaussian noise samples gives a Gaussian with σ_new = σ/√N. Doubling N gives ≈30% noise reduction.","tag":null}
]},
{"id":"l6_2","ch":"l5l7","g":"l5l7-l6","ct":"Lectures 6–7","cs":"Filtering & Edges","sc":null,"tit":"Gaussian Derivatives, Laplacian & Sharpening","b":"L7 · §01","q":[
{"p":"Apply Sobel-x = [[-1,0,1],[-2,0,2],[-1,0,1]] to the centre of [[10,50,90],[20,60,100],[30,70,110]]. Result?","o":["120","200","320","640"],"c":2,"e":"Sum: −10 + 90 − 40 + 200 − 30 + 110 = 320. Strong rightward gradient — the patch is brighter on the right.","tag":null},
{"p":"Why does Sobel produce cleaner edge maps than the simple central difference [−1, 0, 1]?","o":["Sobel uses floating-point arithmetic","Sobel = central difference × [1, 2, 1]^T column smoothing → discrete derivative-of-Gaussian; the smoothing suppresses noise perpendicular to the edge","Sobel has a larger numeric range","Sobel is patented and tuned by Adobe"],"c":1,"e":"The [1, 2, 1] column approximates a 1-D Gaussian. Sobel = differentiate in x AND smooth in y, in a single kernel. Noise is suppressed perpendicular to the differentiation direction.","tag":null},
{"p":"For gradient (f_x, f_y) = (3, 4), what is the edge strength and orientation?","o":["Strength 7, orientation 90°","Strength 5, orientation 53.13°","Strength 25, orientation 36.87°","Strength 5, orientation 36.87°"],"c":1,"e":"|∇f| = √(9 + 16) = 5. θ = atan2(4, 3) ≈ 53.13°. The edge tangent is perpendicular: ≈143°.","tag":null},
{"p":"Which 3×3 kernel sharpens via the Laplacian (4-connected)?","o":["[[0,1,0],[1,4,1],[0,1,0]]","[[0,-1,0],[-1,5,-1],[0,-1,0]]","[[1,1,1],[1,1,1],[1,1,1]]/9","[[-1,-1,-1],[-1,8,-1],[-1,-1,-1]]"],"c":1,"e":"Sharpening kernel = identity − Laplacian = [[0,-1,0],[-1,5,-1],[0,-1,0]]. The −1's subtract the neighbour values and the centre 5 (= 4 + 1) re-injects the original. The 8-connected variant uses centre 9 and −1 surroundings.","tag":null}
]},

{"id":"l8_1","ch":"l8l10","g":"l8l10-l8","ct":"Lectures 8–10","cs":"Inpainting · Compositing · SIFT Detection","sc":null,"tit":"Laplacian vs Patch-Based Inpainting","b":"L8 · §01","q":[
{"p":"Laplacian inpainting solves a sparse linear system Ax = b. For an unknown pixel, what does the matrix A row encode?","o":["Identity row: A[r,r] = 1","Discrete Laplacian: A[r,r] = −4, A[r, r±1] = A[r, r±W] = 1; b[r] = 0","Sobel kernel coefficients","Gaussian weights"],"c":1,"e":"Discrete ∇²f = 0 ⇒ the unknown pixel equals the average of its four neighbours. The row encodes −4·centre + 1·(four neighbours) = 0. Known pixels get identity rows with b = the known value.","tag":null},
{"p":"What background statistic does Laplacian inpainting assume?","o":["Stationary texture","Smoothness — no high-frequency texture in the missing region","Sparse gradients","Self-similar patches"],"c":1,"e":"The membrane interpolant produces a smooth, blob-like fill. It fails on textured regions (brick, foliage, fur) — those need patch-based or learned priors.","tag":null},
{"p":"Freeman-Efros patch-based inpainting matches candidate patches against the target on which pixels?","o":["All pixels (known + unknown)","Only the known (un-masked) pixels of the target patch","Only the unknown pixels","A random subset"],"c":1,"e":"The target overlaps the hole boundary. Matching uses only the known pixels (Euclidean distance over unmasked entries); the best match is pasted, overwriting only the unknown pixels — known pixels are preserved to avoid boundary artefacts.","tag":null},
{"p":"Both Laplacian and patch-based inpainting fail when:","o":["The hole is smaller than 3×3","The hole is large AND contains semantic content not present elsewhere in the image","The image is in greyscale","The hole touches the image boundary"],"c":1,"e":"Neither smoothness nor texture-stationarity captures novel semantic content (e.g. a missing eye on a face when no other eye is visible). Modern learned priors (partial-conv UNet, DeepFill, LaMa, diffusion inpainters) supply that knowledge.","tag":null}
]},

{"id":"l9_1","ch":"l8l10","g":"l8l10-l9","ct":"Lecture 9","cs":"Compositing & Seam Carving","sc":null,"tit":"Porter-Duff, Poisson Compositing & Seam Carving","b":"L9 · §01","q":[
{"p":"Porter-Duff 'A over B' output alpha is:","o":["α_out = αA · αB","α_out = αA + αB · (1 − αA)","α_out = max(αA, αB)","α_out = (αA + αB) / 2"],"c":1,"e":"Source coverage αA plus destination coverage αB scaled by (1 − αA) — the destination only shows through where the source is not opaque. Colour follows the same coefficient pattern, divided by α_out to un-premultiply.","tag":null},
{"p":"Why does Poisson (gradient-domain) compositing tolerate an imprecise matte?","o":["It uses Porter-Duff under the hood","It transfers source gradients, not source colours; the matte boundary smoothly absorbs the destination's colour","It interpolates with bi-cubic","It applies a Gaussian blur to the matte"],"c":1,"e":"Solving ∇²f_dest = ∇²f_source inside the matte with Dirichlet boundary conditions means the colour at the boundary is dictated by the destination. Slight matte errors are invisible because the colour transitions smoothly across them.","tag":null},
{"p":"Compared to Laplacian inpainting, how does the Poisson compositing linear system differ?","o":["The matrix A is different; b is the same","A is identical (discrete Laplacian rows for unknowns); b uses the source Laplacian at corresponding pixels instead of 0","Both A and b are completely different","Poisson does not use Ax = b"],"c":1,"e":"Only the RHS changes. Inpainting wants ∇²f = 0 (b = 0 for unknowns). Compositing wants ∇²f = ∇²(source), so b at unknowns = the source's Laplacian at the corresponding pixel. Same sparse machinery.","tag":null},
{"p":"Seam carving's vertical-seam recurrence is:","o":["M(i,j) = E(i,j) + M(i−1, j)","M(i,j) = E(i,j) + min(M(i−1, j−1), M(i−1, j), M(i−1, j+1))","M(i,j) = max(E(i,j), M(i−1, j))","M(i,j) = E(i,j) · M(i−1, j)"],"c":1,"e":"Dynamic-programming recurrence: a seam can shift at most one column per row (8-connectivity). The minimum value in the bottom row indicates the optimal seam's cost; backtrack to trace it.","tag":null},
{"p":"A common failure mode of vanilla seam carving:","o":["Always removes the same column","Energy map mis-ranks salient regions (e.g. a dark face) → seams cut through important content","Cannot be parallelised","Works only on RGB, not greyscale"],"c":1,"e":"Gradient-magnitude energy may under-weight salient objects with low local contrast (a dark face on a bright background). Remedies: combine with a face/saliency detector; forward-energy formulations; user-supplied 'preservation' or 'removal' masks.","tag":null}
]},

{"id":"l10_1","ch":"l8l10","g":"l8l10-l10","ct":"Lecture 10","cs":"Edges, Scale-Space & SIFT Detection","sc":null,"tit":"Canny, Scale-Space & SIFT Keypoints","b":"L10 · §01","q":[
{"p":"What does non-maximum suppression do in the Canny pipeline?","o":["Removes weak edges below a threshold","Thins ridges to single-pixel-wide edges by keeping only local maxima along the gradient direction","Smooths the gradient magnitude","Links edge fragments into contours"],"c":1,"e":"For each pixel, look at the two neighbours along the gradient direction (perpendicular to the edge). Keep the pixel only if its magnitude exceeds both. Result: single-pixel-wide edge ridges localised at the magnitude peak.","tag":null},
{"p":"Canny's hysteresis thresholding uses:","o":["A single threshold T","Two thresholds T_H > T_L; weak edges (between T_L and T_H) survive only if connected to a strong edge","Three thresholds chosen by Otsu","A learned per-pixel threshold"],"c":1,"e":"Strong edges (g > T_H) are definitely on; non-edges (g < T_L) are off; weak edges retained iff 8-connected to a strong edge directly or transitively. Suppresses isolated noise spikes while preserving real contours that briefly dip below T_H.","tag":null},
{"p":"SIFT detects keypoints as local extrema in:","o":["A 1-D gradient profile","A 2-D Sobel magnitude map","A 3-D (x, y, σ) DoG/LoG scale-space cube — each pixel compared to its 26 neighbours","A 4-D (x, y, scale, orientation) tensor"],"c":2,"e":"DoG (Difference of Gaussians, a cheap LoG approximation) is computed across octave-spaced scales. A candidate keypoint must be a local extremum versus its 8 spatial neighbours at the same scale AND 9 neighbours at each adjacent scale = 26 total.","tag":null},
{"p":"Why is σ associated with each SIFT keypoint?","o":["To control the magnitude threshold","So the SIFT descriptor window can be sized in proportion to σ — giving scale invariance","To filter out duplicate detections","It is unused; just metadata"],"c":1,"e":"The detected σ tells the descriptor stage the natural scale of the feature. Sizing the descriptor window proportionally to σ means matching is invariant to the absolute scale of the image (e.g. zooming in/out by ~2×).","tag":null},
{"p":"Edges that persist across multiple Gaussian scales tend to be:","o":["Noise","Texture detail","Salient structural edges (object boundaries)","Quantisation artefacts"],"c":2,"e":"Real object boundaries survive heavy blurring; shadows, noise and fine texture vanish quickly. Persistence across scales is the heuristic that motivates scale-space pyramids and SIFT-style scale selection.","tag":null}
]},

{"id":"l11_1","ch":"l11","g":"l11-core","ct":"Lecture 11","cs":"Descriptors: HOG, SIFT, BoVW, VLAD","sc":null,"tit":"Descriptors & Retrieval Pipelines","b":"L11 · §01","q":[
{"p":"Dimensionality of a SIFT descriptor with default parameters (n=4 cells per side, q=8 orientation bins)?","o":["32","64","128","256"],"c":2,"e":"4×4 cells × 8 bins = 128-D. Footprint (n × w_pixels)² where w_pixels scales with σ; the 128-D descriptor lives on a 16-px-equivalent grid around the keypoint after scale + rotation normalisation.","tag":null},
{"p":"For HOG with parameters w = 5 (cells/side), n = 16 (pixels/cell), q = 9 (orientation bins) — what is the spatial footprint and descriptor dimension?","o":["40×40, 45-D","80×80, 225-D","16×16, 81-D","100×100, 100-D"],"c":1,"e":"Footprint = (n·w)² = 80×80 pixels. Dimensionality = q·w² = 9·25 = 225-D.","tag":null},
{"p":"In the SIFT matching pipeline, what is the distance-ratio test?","o":["Reject any match whose L2 distance exceeds 0.5","Discard matches where the second-closest descriptor's distance is less than ~1.4× the closest — the match is ambiguous","Accept only matches that pass under L1 distance","Average the top-5 nearest-neighbour distances"],"c":1,"e":"If two database descriptors are nearly equidistant from the query, the match is unreliable. Lowe's threshold (often expressed as ratio < 0.8, equivalently second/first > 1.25–1.4) discards ambiguous matches.","tag":null},
{"p":"Why can a VLAD descriptor with k = 64 clusters outperform a BoVW histogram with k = 1000 clusters?","o":["VLAD uses a smarter clustering algorithm","VLAD stores the mean residual within each cluster (d=128 numbers/cluster), preserving within-cluster geometry; BoVW only stores counts","BoVW has too much information","VLAD uses L1 distance instead of L2"],"c":1,"e":"BoVW: 1 count/cluster, throws away within-cluster geometry. VLAD: d-D residual/cluster, captures where in the cluster descriptors sit. With k=64, d=128 → 8192-D VLAD vs 1000-D BoVW — VLAD has more discriminative information per image.","tag":null}
]}
];
